import { useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { QueryClient, QueryClientProvider, useQueryClient } from '@tanstack/react-query';
import { Link, Route, Router as WouterRouter, Switch, useLocation } from 'wouter';
import { Activity, AlertCircle, ArrowLeft, BookOpen, CalendarCheck, Check, ChevronDown, ClipboardList, GraduationCap, LayoutDashboard, Menu, Pencil, Plus, Search, Settings2, Sparkles, Trash2, Users, X } from 'lucide-react';
import { useCreateStudent, useCreateTeacher, useDeleteStudent, useGetActivity, useGetDashboardSummary, useListAttendance, useListStudents, useListTeachers, useRecordAttendance, useUpdateStudent, useUpdateTeacher, getGetActivityQueryKey, getGetDashboardSummaryQueryKey, getListAttendanceQueryKey, getListStudentsQueryKey, getListTeachersQueryKey } from '@workspace/api-client-react';
import type { AttendanceRecord, Student, Teacher } from '@workspace/api-client-react';
import NotFound from '@/pages/not-found';
import logoAsset from '@assets/68aebd1177e203ded722cb6fb392d53f684b0ea0112396a73153f9ee7969f1_1786411553048.png';

const queryClient = new QueryClient();
const navItems = [
  { href: '/', label: 'نظرة عامة', icon: LayoutDashboard },
  { href: '/students', label: 'الطلاب', icon: GraduationCap },
  { href: '/teachers', label: 'المعلّمون', icon: Users },
  { href: '/attendance', label: 'الحضور والغياب', icon: CalendarCheck },
];
const statusLabels: Record<string, string> = { active: 'نشط', paused: 'متوقف مؤقتاً', completed: 'مكتمل', on_leave: 'في إجازة', present: 'حاضر', absent: 'غائب', late: 'متأخر', excused: 'بعذر' };
const getInitials = (name: string) => name.trim().split(/\s+/).slice(0, 2).map((word) => word[0]).join('');
const formatDate = (value?: string) => value ? new Intl.DateTimeFormat('ar-SA', { day: 'numeric', month: 'short' }).format(new Date(value)) : '—';
const formatTime = (value?: string) => value ? new Intl.DateTimeFormat('ar-SA', { hour: 'numeric', minute: '2-digit' }).format(new Date(value)) : '—';

function Shell({ children }: { children: ReactNode }) {
  const [location] = useLocation();
  const [mobileOpen, setMobileOpen] = useState(false);
  return <div className="app-shell" dir="rtl">
    <aside className="sidebar">
       <Link href="/" className="brand" data-testid="link-brand"><span className="brand-logo"><img src={logoAsset} alt="شعار مقرأة سُحُب" /></span><span><div className="brand-title">مقرأة سُحُب</div><div className="brand-subtitle">منصة إدارة التعلّم</div></span></Link>
      <div className="nav-label">المساحة الإدارية</div>
      <nav className="nav-list">{navItems.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={`nav-link ${location === href ? 'active' : ''}`} data-testid={`link-nav-${href === '/' ? 'overview' : href.slice(1)}`}><Icon size={18} strokeWidth={1.8} /><span>{label}</span></Link>)}</nav>
      <div className="sidebar-foot"><div className="side-note"><Sparkles size={14} /> <span>مساحة آمنة للنمو</span></div><div>تابع أثر كل حلقة، وامنح كل طالب عناية تليق برحلته.</div></div>
    </aside>
    <div className="main-area">
      <header className="topbar"><button className="mobile-menu" onClick={() => setMobileOpen((value) => !value)} aria-label="فتح القائمة" data-testid="button-mobile-menu"><Menu size={21} /></button><div className="topbar-meta">{new Intl.DateTimeFormat('ar-SA', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date())}</div><div className="user-chip"><div><div className="user-name">إدارة المقرأة</div><div className="user-role">المشرف العام</div></div><div className="avatar">م</div></div></header>
      {mobileOpen && <div className="mobile-nav">{navItems.map(({ href, label, icon: Icon }) => <Link key={href} href={href} onClick={() => setMobileOpen(false)} className={`nav-link ${location === href ? 'active' : ''}`} data-testid={`link-mobile-nav-${href === '/' ? 'overview' : href.slice(1)}`}><Icon size={18} /><span>{label}</span></Link>)}</div>}
      {children}
    </div>
  </div>;
}

function LoadingBlock({ rows = 4 }: { rows?: number }) { return <div className="card table-card" data-testid="loading-state">{Array.from({ length: rows }).map((_, index) => <div key={index} className="skeleton" style={{ height: 62, margin: 1 }} />)}</div>; }
function ErrorState({ onRetry }: { onRetry?: () => void }) { return <div className="card error-state" data-testid="error-state"><AlertCircle size={31} /><div className="empty-title">حدث تعذّر مؤقت</div><div className="empty-copy">لم نتمكن من استدعاء البيانات الآن. جرّب مرة أخرى بعد لحظات.</div>{onRetry && <button className="button button-secondary" onClick={onRetry} data-testid="button-retry">إعادة المحاولة</button>}</div>; }
function EmptyState({ title, copy, action }: { title: string; copy: string; action?: React.ReactNode }) { return <div className="empty-state" data-testid="empty-state"><div className="empty-icon"><BookOpen size={25} /></div><div className="empty-title">{title}</div><div className="empty-copy">{copy}</div>{action}</div>; }
function PageHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-heading animate-rise"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p className="page-description">{description}</p></div>{action}</div>; }
function StatusBadge({ value }: { value?: string }) { return <span className={`badge badge-${value}`} data-testid={`status-${value}`}>{statusLabels[value || ''] || value}</span>; }
function Toast({ message, onClose }: { message: string; onClose: () => void }) { return <div className="toast-message" role="status" onClick={onClose} data-testid="toast-message"><Check size={14} style={{ verticalAlign: 'middle', marginLeft: 6 }} />{message}</div>; }

function Dashboard() {
  const summary = useGetDashboardSummary();
  const activity = useGetActivity({ limit: 6 });
  const stats = summary.data;
   return <main className="page-wrap">
    <PageHeading eyebrow="صباح الخير، إدارة المقرأة" title="أثرٌ يُرى، وعنايةٌ تُبنى" description="نظرة هادئة على نبض مجتمع سُحُب التعليمي اليوم." action={<Link href="/attendance" className="button button-primary" data-testid="button-go-attendance"><ClipboardList size={16} /> تسجيل حضور اليوم</Link>} />
     <div className="signal-banner animate-rise" data-testid="dashboard-signal"><div className="signal-copy"><div className="signal-mark"><Sparkles size={16} /></div><div><strong>مساحتك اليومية جاهزة للمتابعة</strong><span>تفقّد المؤشرات الأساسية، ثم اقترب من التفاصيل التي تحتاج قرارك.</span></div></div><Link href="/students" className="button button-secondary" data-testid="button-review-students">مراجعة الطلاب</Link></div>
    {summary.isLoading ? <div className="stat-grid">{Array.from({ length: 4 }).map((_, i) => <div className="card stat-card skeleton" key={i} style={{ height: 142 }} />)}</div> : summary.isError ? <ErrorState onRetry={() => summary.refetch()} /> : stats && <><div className="stat-grid animate-rise delay-1">
      <Stat label="إجمالي الطلاب" value={stats.studentsCount} foot={`${stats.activeStudentsCount} طالباً في رحلة نشطة`} />
      <Stat label="المعلّمون" value={stats.teachersCount} foot="فريق يعلّم بأثر" />
      <Stat label="نسبة الحضور" value={`${stats.attendanceRate}%`} foot="متوسط آخر 30 يوماً" />
      <Stat label="تقدّم هذا الشهر" value={`${stats.monthlyProgress}%`} foot="تحسّن عن الشهر السابق" />
    </div><div className="dashboard-grid animate-rise delay-2">
      <section className="card wide-card"><div className="card-heading"><div><div className="card-title">إيقاع الحضور الأسبوعي</div><div className="card-subtitle">نسبة الالتزام في حلقات هذا الأسبوع</div></div><span className="badge badge-present">هذا الأسبوع</span></div><WeeklyChart values={stats.weeklyAttendance || []} /></section>
      <section className="card wide-card"><div className="card-heading"><div><div className="card-title">توزيع المستويات</div><div className="card-subtitle">عدد الطلاب في كل مستوى</div></div><GraduationCap size={19} color="hsl(13 56% 52%)" /></div><Breakdown values={stats.levelBreakdown || []} /></section>
    </div></>}
    <div className="bottom-grid animate-rise delay-3"><section className="card wide-card"><div className="card-heading"><div><div className="card-title">آخر ما جرى</div><div className="card-subtitle">إشارات صغيرة تصنع الصورة كاملة</div></div><Activity size={18} color="hsl(13 56% 52%)" /></div>{activity.isLoading ? <div className="skeleton" style={{ height: 190 }} /> : activity.isError ? <ErrorState onRetry={() => activity.refetch()} /> : !activity.data?.length ? <EmptyState title="لا توجد أنشطة بعد" copy="ستظهر هنا آخر مستجدات مجتمع المقرأة." /> : <ActivityList items={activity.data} />}</section><section className="card wide-card"><div className="card-heading"><div><div className="card-title">بوابة المتابعة</div><div className="card-subtitle">اختصارات إلى أكثر ما يحتاج انتباهك</div></div><Settings2 size={18} color="hsl(13 56% 52%)" /></div><div className="breakdown-list"><QuickLink href="/students" icon={<GraduationCap size={18} />} title="استعراض الطلاب" copy="راجع تقدّم الطلاب وحالاتهم الحالية" /><QuickLink href="/teachers" icon={<Users size={18} />} title="فريق التعليم" copy="تعرّف على توزيع الأدوار والحلقات" /><QuickLink href="/attendance" icon={<CalendarCheck size={18} />} title="سجل الحضور" copy="أضف سجلاً أو راجع تاريخ الالتزام" /></div></section></div>
  </main>;
}
function Stat({ label, value, foot }: { label: string; value: string | number; foot: string }) { return <div className="card stat-card"><div className="stat-label">{label}</div><div className="stat-number" data-testid={`stat-${label}`}>{value}</div><div className="stat-foot">{foot}</div></div>; }
function WeeklyChart({ values }: { values: { day: string; rate: number }[] }) { const max = Math.max(...values.map((v) => v.rate), 1); return <div className="chart-area">{values.map((item) => <div className="chart-col" key={item.day}><span className="chart-value">{item.rate}%</span><div className="chart-bar" style={{ height: `${Math.max(8, (item.rate / max) * 135)}px` }} /><span className="chart-label">{item.day}</span></div>)}</div>; }
function Breakdown({ values }: { values: { level: string; count: number }[] }) { const max = Math.max(...values.map((v) => v.count), 1); return <div className="breakdown-list">{values.length ? values.map((item) => <div className="breakdown-item" key={item.level}><div className="breakdown-label"><span>{item.level}</span><strong>{item.count}</strong></div><div className="breakdown-track"><div className="breakdown-fill" style={{ width: `${(item.count / max) * 100}%` }} /></div></div>) : <EmptyState title="لا بيانات كافية" copy="سيظهر التوزيع بعد تسجيل الطلاب." />}</div>; }
function ActivityList({ items }: { items: { id: number; title: string; description: string; createdAt: string; type: string }[] }) { const icons: Record<string, ReactNode> = { student_joined: <GraduationCap size={15} />, attendance_recorded: <CalendarCheck size={15} />, progress_updated: <Sparkles size={15} />, teacher_joined: <Users size={15} /> }; return <div className="activity-list">{items.map((item) => <div className="activity-row" key={item.id} data-testid={`activity-${item.id}`}><div className="activity-icon">{icons[item.type] || <Activity size={15} />}</div><div><div className="activity-title">{item.title}</div><div className="activity-desc">{item.description}</div></div><div className="activity-time">{formatTime(item.createdAt)}</div></div>)}</div>; }
function QuickLink({ href, icon, title, copy }: { href: string; icon: ReactNode; title: string; copy: string }) { return <Link href={href} className="activity-row" data-testid={`quick-link-${href.slice(1)}`}><div className="activity-icon">{icon}</div><div><div className="activity-title">{title}</div><div className="activity-desc">{copy}</div></div><ArrowLeft size={15} color="hsl(166 12% 43%)" /></Link>; }

function StudentsPage() {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [modal, setModal] = useState<Student | null | false>(false); const [toast, setToast] = useState('');
  const query = useListStudents({ search: search || undefined, status: status ? status as 'active' | 'paused' | 'completed' : undefined }); const invalidate = useQueryClient(); const del = useDeleteStudent();
  const refresh = () => invalidate.invalidateQueries({ queryKey: getListStudentsQueryKey() });
  const onDelete = (student: Student) => { if (window.confirm(`حذف سجل ${student.name}؟ لا يمكن التراجع عن هذا الإجراء.`)) del.mutate({ id: student.id }, { onSuccess: () => { refresh(); setToast('تم حذف سجل الطالب'); }, onError: () => setToast('تعذر حذف السجل') }); };
  return <main className="page-wrap"><PageHeading eyebrow="دليل المجتمع" title="الطلاب" description="كل رحلة لها إيقاعها. ابق قريباً من التفاصيل التي تصنع الفرق." action={<button className="button button-primary" onClick={() => setModal(null)} data-testid="button-add-student"><Plus size={17} /> إضافة طالب</button>} />
    <div className="toolbar"><div className="searchbox"><Search size={17} /><input className="input" type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="ابحث باسم الطالب أو البريد..." data-testid="input-search-students" /></div><select className="select" value={status} onChange={(e) => setStatus(e.target.value)} style={{ width: 170 }} data-testid="select-student-status"><option value="">كل الحالات</option><option value="active">نشط</option><option value="paused">متوقف مؤقتاً</option><option value="completed">مكتمل</option></select></div>
    {query.isLoading ? <LoadingBlock /> : query.isError ? <ErrorState onRetry={() => query.refetch()} /> : <div className="card table-card">{!query.data?.length ? <EmptyState title="لا يوجد طلاب مطابقون" copy={search ? 'جرّب كلمة بحث أخرى أو أضف طالباً جديداً.' : 'ابدأ ببناء مجتمع المقرأة وإضافة أول طالب.'} action={<button className="button button-primary" onClick={() => setModal(null)} data-testid="button-empty-add-student"><Plus size={16} /> إضافة طالب</button>} /> : <StudentTable students={query.data} onEdit={setModal} onDelete={onDelete} />}</div>}
    {modal !== false && <StudentModal student={modal} onClose={() => setModal(false)} onSaved={() => { setModal(false); refresh(); setToast(modal ? 'تم حفظ تعديلات الطالب' : 'تمت إضافة الطالب إلى المقرأة'); }} />}
    {toast && <Toast message={toast} onClose={() => setToast('')} />}
  </main>;
}
function StudentTable({ students, onEdit, onDelete }: { students: Student[]; onEdit: (student: Student) => void; onDelete: (student: Student) => void }) { return <div className="table-scroll"><table className="data-table"><thead><tr><th>الطالب</th><th>المستوى</th><th>التقدم</th><th>الحضور</th><th>الحالة</th><th>انضم في</th><th>إجراء</th></tr></thead><tbody>{students.map((student) => <tr key={student.id} data-testid={`row-student-${student.id}`}><td><div className="person"><div className="person-avatar">{getInitials(student.name)}</div><div><div className="person-name">{student.name}</div><div className="person-meta">{student.email}</div></div></div></td><td>{student.level}</td><td><div className="progress-line"><span>{student.progress}%</span><div className="progress-track"><div className="progress-fill" style={{ width: `${student.progress}%` }} /></div></div></td><td>{student.attendanceRate}%</td><td><StatusBadge value={student.status} /></td><td>{formatDate(student.joinedAt)}</td><td><div className="actions"><button className="icon-button" onClick={() => onEdit(student)} aria-label="تعديل الطالب" data-testid={`button-edit-student-${student.id}`}><Pencil size={15} /></button><button className="icon-button danger" onClick={() => onDelete(student)} aria-label="حذف الطالب" data-testid={`button-delete-student-${student.id}`}><Trash2 size={15} /></button></div></td></tr>)}</tbody></table></div>; }

function StudentModal({ student, onClose, onSaved }: { student: Student | null; onClose: () => void; onSaved: () => void }) {
  const create = useCreateStudent(); const update = useUpdateStudent(); const [form, setForm] = useState({ name: student?.name || '', email: student?.email || '', phone: student?.phone || '', level: student?.level || '', status: student?.status || 'active' });
  const submit = (e: FormEvent) => { e.preventDefault(); if (!form.name.trim() || !form.email.trim() || !form.level.trim()) return; const data = { ...form, phone: form.phone || null }; if (student) update.mutate({ id: student.id, data }, { onSuccess: onSaved }); else create.mutate({ data }, { onSuccess: onSaved }); };
  const busy = create.isPending || update.isPending; return <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><form className="modal" onSubmit={submit} data-testid="form-student"><div className="modal-header"><div><div className="modal-title">{student ? 'تعديل بيانات الطالب' : 'طالب جديد'}</div><div className="modal-copy">أدخل البيانات الأساسية للمتابعة اليومية.</div></div><button type="button" className="icon-button" onClick={onClose} aria-label="إغلاق" data-testid="button-close-student-modal"><X size={18} /></button></div><div className="modal-body"><div className="form-grid"><Field label="الاسم الكامل" value={form.name} onChange={(value) => setForm({ ...form, name: value })} placeholder="مثال: عبد الرحمن سالم" testId="input-student-name" /><Field label="البريد الإلكتروني" value={form.email} onChange={(value) => setForm({ ...form, email: value })} placeholder="name@example.com" testId="input-student-email" type="email" /><Field label="رقم الجوال" value={form.phone} onChange={(value) => setForm({ ...form, phone: value })} placeholder="اختياري" testId="input-student-phone" /><Field label="المستوى" value={form.level} onChange={(value) => setForm({ ...form, level: value })} placeholder="مثال: جزء عمّ" testId="input-student-level" /><div className="field"><label className="field-label">الحالة</label><select className="select" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as typeof form.status })} data-testid="select-student-form-status"><option value="active">نشط</option><option value="paused">متوقف مؤقتاً</option><option value="completed">مكتمل</option></select></div></div><div className="modal-footer"><button className="button button-primary" disabled={busy} type="submit" data-testid="button-submit-student">{busy ? 'جارٍ الحفظ...' : student ? 'حفظ التعديلات' : 'إضافة الطالب'}</button><button className="button button-secondary" type="button" onClick={onClose} data-testid="button-cancel-student">إلغاء</button></div></div></form></div>;
}
function Field({ label, value, onChange, placeholder, testId, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; testId: string; type?: string }) { return <div className="field"><label className="field-label">{label}</label><input className="input" type={type} value={value} placeholder={placeholder} onChange={(e) => onChange(e.target.value)} data-testid={testId} required={label !== 'رقم الجوال'} /></div>; }

function TeachersPage() {
  const [modal, setModal] = useState<Teacher | null | false>(false); const [toast, setToast] = useState(''); const query = useListTeachers(); const client = useQueryClient();
  return <main className="page-wrap"><PageHeading eyebrow="أهل الذكر والتعليم" title="المعلّمون" description="فريق يرافق الحفظ بالفهم، ويصنع من الاستمرارية عادة." action={<button className="button button-primary" onClick={() => setModal(null)} data-testid="button-add-teacher"><Plus size={17} /> إضافة معلّم</button>} />{query.isLoading ? <LoadingBlock rows={3} /> : query.isError ? <ErrorState onRetry={() => query.refetch()} /> : <div className="card table-card">{!query.data?.length ? <EmptyState title="فريقك يبدأ من هنا" copy="أضف المعلّم الأول لتبدأ بإدارة حلقاتك." action={<button className="button button-primary" onClick={() => setModal(null)} data-testid="button-empty-add-teacher"><Plus size={16} /> إضافة معلّم</button>} /> : <TeacherTable teachers={query.data} onEdit={setModal} />}</div>}{modal !== false && <TeacherModal teacher={modal} onClose={() => setModal(false)} onSaved={() => { setModal(false); client.invalidateQueries({ queryKey: getListTeachersQueryKey() }); setToast(modal ? 'تم حفظ تعديلات المعلّم' : 'تمت إضافة المعلّم'); }} />}{toast && <Toast message={toast} onClose={() => setToast('')} />}</main>;
}
function TeacherTable({ teachers, onEdit }: { teachers: Teacher[]; onEdit: (teacher: Teacher) => void }) { return <div className="table-scroll"><table className="data-table"><thead><tr><th>المعلّم</th><th>التخصص</th><th>عدد الطلاب</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{teachers.map((teacher) => <tr key={teacher.id} data-testid={`row-teacher-${teacher.id}`}><td><div className="person"><div className="person-avatar">{getInitials(teacher.name)}</div><div><div className="person-name">{teacher.name}</div><div className="person-meta">{teacher.email}</div></div></div></td><td>{teacher.specialty}</td><td>{teacher.studentsCount} طالباً</td><td><StatusBadge value={teacher.status} /></td><td><button className="icon-button" onClick={() => onEdit(teacher)} aria-label="تعديل المعلّم" data-testid={`button-edit-teacher-${teacher.id}`}><Pencil size={15} /></button></td></tr>)}</tbody></table></div>; }
function TeacherModal({ teacher, onClose, onSaved }: { teacher: Teacher | null; onClose: () => void; onSaved: () => void }) { const create = useCreateTeacher(); const update = useUpdateTeacher(); const [form, setForm] = useState({ name: teacher?.name || '', email: teacher?.email || '', specialty: teacher?.specialty || '', status: teacher?.status || 'active' }); const submit = (e: FormEvent) => { e.preventDefault(); if (!form.name.trim() || !form.email.trim() || !form.specialty.trim()) return; if (teacher) update.mutate({ id: teacher.id, data: form }, { onSuccess: onSaved }); else create.mutate({ data: form }, { onSuccess: onSaved }); }; const busy = create.isPending || update.isPending; return <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><form className="modal" onSubmit={submit} data-testid="form-teacher"><div className="modal-header"><div><div className="modal-title">{teacher ? 'تعديل بيانات المعلّم' : 'معلّم جديد'}</div><div className="modal-copy">بيانات الظهور الأساسية في دليل الفريق.</div></div><button type="button" className="icon-button" onClick={onClose} aria-label="إغلاق" data-testid="button-close-teacher-modal"><X size={18} /></button></div><div className="modal-body"><div className="form-grid"><Field label="الاسم الكامل" value={form.name} onChange={(value) => setForm({ ...form, name: value })} placeholder="مثال: أ. فاطمة الزهراء" testId="input-teacher-name" /><Field label="البريد الإلكتروني" type="email" value={form.email} onChange={(value) => setForm({ ...form, email: value })} placeholder="name@example.com" testId="input-teacher-email" /><Field label="التخصص" value={form.specialty} onChange={(value) => setForm({ ...form, specialty: value })} placeholder="مثال: التجويد والإقراء" testId="input-teacher-specialty" /><div className="field"><label className="field-label">الحالة</label><select className="select" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as typeof form.status })} data-testid="select-teacher-form-status"><option value="active">نشط</option><option value="on_leave">في إجازة</option></select></div></div><div className="modal-footer"><button className="button button-primary" disabled={busy} type="submit" data-testid="button-submit-teacher">{busy ? 'جارٍ الحفظ...' : teacher ? 'حفظ التعديلات' : 'إضافة المعلّم'}</button><button className="button button-secondary" type="button" onClick={onClose} data-testid="button-cancel-teacher">إلغاء</button></div></div></form></div>; }

function AttendancePage() {
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [studentId, setStudentId] = useState(''); const [modal, setModal] = useState(false); const [toast, setToast] = useState('');
  const query = useListAttendance({ date: date || undefined, studentId: studentId ? Number(studentId) : undefined }); const students = useListStudents(); const client = useQueryClient();
  const refresh = () => client.invalidateQueries({ queryKey: getListAttendanceQueryKey() });
  return <main className="page-wrap"><PageHeading eyebrow="المتابعة اليومية" title="الحضور والغياب" description="سجل الحضور بلطف، لتعرف أين يحتاج كل طالب إلى مساندة." action={<button className="button button-primary" onClick={() => setModal(true)} data-testid="button-record-attendance"><Plus size={17} /> تسجيل حضور</button>} /><div className="toolbar"><input className="input date-input" type="date" value={date} onChange={(e) => setDate(e.target.value)} style={{ width: 170 }} data-testid="input-attendance-date" /><select className="select" value={studentId} onChange={(e) => setStudentId(e.target.value)} style={{ width: 200 }} data-testid="select-attendance-student"><option value="">كل الطلاب</option>{students.data?.map((student) => <option key={student.id} value={student.id}>{student.name}</option>)}</select></div>{query.isLoading ? <LoadingBlock /> : query.isError ? <ErrorState onRetry={() => query.refetch()} /> : <div className="card table-card">{!query.data?.length ? <EmptyState title="لا توجد سجلات لهذا اليوم" copy="ابدأ بتسجيل حضور الطلاب، وستبقى التفاصيل هنا للمتابعة." action={<button className="button button-primary" onClick={() => setModal(true)} data-testid="button-empty-record-attendance"><Plus size={16} /> تسجيل حضور</button>} /> : <AttendanceTable records={query.data} />}</div>}{modal && <AttendanceModal students={students.data || []} defaultDate={date} onClose={() => setModal(false)} onSaved={() => { setModal(false); refresh(); client.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() }); client.invalidateQueries({ queryKey: getGetActivityQueryKey({ limit: 6 }) }); setToast('تم تسجيل الحضور بنجاح'); }} />}{toast && <Toast message={toast} onClose={() => setToast('')} />}</main>;
}
function AttendanceTable({ records }: { records: AttendanceRecord[] }) { return <div className="table-scroll"><table className="data-table"><thead><tr><th>الطالب</th><th>التاريخ</th><th>الحالة</th><th>ملاحظة</th></tr></thead><tbody>{records.map((record) => <tr key={record.id} data-testid={`row-attendance-${record.id}`}><td><div className="person"><div className="person-avatar">{getInitials(record.studentName)}</div><div className="person-name">{record.studentName}</div></div></td><td>{formatDate(record.date)}</td><td><StatusBadge value={record.status} /></td><td style={{ color: 'hsl(var(--muted-foreground))' }}>{record.note || '—'}</td></tr>)}</tbody></table></div>; }
function AttendanceModal({ students, defaultDate, onClose, onSaved }: { students: Student[]; defaultDate: string; onClose: () => void; onSaved: () => void }) { const record = useRecordAttendance(); const [form, setForm] = useState({ studentId: students[0]?.id?.toString() || '', date: defaultDate, status: 'present', note: '' }); const submit = (e: FormEvent) => { e.preventDefault(); if (!form.studentId) return; record.mutate({ data: { studentId: Number(form.studentId), date: form.date, status: form.status as 'present' | 'absent' | 'late' | 'excused', note: form.note || null } }, { onSuccess: onSaved }); }; return <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><form className="modal" onSubmit={submit} data-testid="form-attendance"><div className="modal-header"><div><div className="modal-title">تسجيل حضور</div><div className="modal-copy">سجل واحد، واطمئنان أكبر على سير الحلقة.</div></div><button type="button" className="icon-button" onClick={onClose} aria-label="إغلاق" data-testid="button-close-attendance-modal"><X size={18} /></button></div><div className="modal-body"><div className="form-grid"><div className="field full"><label className="field-label">الطالب</label><select className="select" value={form.studentId} onChange={(e) => setForm({ ...form, studentId: e.target.value })} data-testid="select-record-student"><option value="">اختر الطالب</option>{students.map((student) => <option key={student.id} value={student.id}>{student.name}</option>)}</select></div><div className="field"><label className="field-label">التاريخ</label><input className="input date-input" type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} data-testid="input-record-date" /></div><div className="field"><label className="field-label">الحالة</label><select className="select" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })} data-testid="select-record-status"><option value="present">حاضر</option><option value="late">متأخر</option><option value="absent">غائب</option><option value="excused">بعذر</option></select></div><div className="field full"><label className="field-label">ملاحظة</label><textarea className="textarea" value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} placeholder="أضف سياقاً مفيداً للمتابعة..." data-testid="textarea-record-note" /></div></div><div className="modal-footer"><button className="button button-primary" disabled={record.isPending || !students.length} type="submit" data-testid="button-submit-attendance">{record.isPending ? 'جارٍ التسجيل...' : 'حفظ السجل'}</button><button className="button button-secondary" type="button" onClick={onClose} data-testid="button-cancel-attendance">إلغاء</button></div></div></form></div>; }

function Router() { return <Shell><Switch><Route path="/" component={Dashboard} /><Route path="/students" component={StudentsPage} /><Route path="/teachers" component={TeachersPage} /><Route path="/attendance" component={AttendancePage} /><Route component={NotFound} /></Switch></Shell>; }
function App() { return <QueryClientProvider client={queryClient}><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, '')}><Router /></WouterRouter></QueryClientProvider>; }
export default App;